---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: zhadow/cc-docker
    tag: latest

inputs:
- name: concourse-creator

run:
  path: pipeline/tasks/bosh.sh
  dir: concourse-creator

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION:
  AWS_AZ:
  BOSH_PASSWORD:
  AWS_KEYPAIR_KEY_NAME:
  PRIVATE_KEY_PATH: